# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Nuget Package

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: RoutyaBuild

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore Routya.ConfigKit dependencies
      run: dotnet restore Routya.ConfigKit/Routya.ConfigKit.csproj
      
    - name: Build Routya.ConfigKit
      run: dotnet build Routya.ConfigKit/Routya.ConfigKit.csproj --configuration Release --no-restore

    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
    - name: Pack Routya.ConfigKit
      run: dotnet pack Routya.ConfigKit/Routya.ConfigKit.csproj --configuration Release /p:PackageVersion=${{ env.VERSION }} --no-build --output ./nupkgs

    - name: Push Routya.ConfigKit to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
